/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgendaPlaceholder: typeof import('./src/components/AgendaPlaceholder.vue')['default']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardHeader: typeof import('bootstrap-vue-next/components/BCard')['BCardHeader']
    BCardTitle: typeof import('bootstrap-vue-next/components/BCard')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BLink: typeof import('bootstrap-vue-next/components/BLink')['BLink']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    CreateTicketPlaceholder: typeof import('./src/components/CreateTicketPlaceholder.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    TicketsPlaceholder: typeof import('./src/components/TicketsPlaceholder.vue')['default']
  }
}
